version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: mindlink-postgres
    restart: always
    environment:
      POSTGRES_USER: mindlink
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mindlinkdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mindlink-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"     # za aplikaciju (AMQP)
      - "15672:15672"   # management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:
